"""
Test Processor Node

This node demonstrates using a custom type from another library.
It uses TestData from test_a library.
"""

from haywire.core.node.base import BaseNode
from haywire.core.node.decorator import node

@node(
    label='Test Processor',
    description='Processes TestData from test_a library',
    search_tags=['test', 'processor', 'cross-library'],
    menu='test_b/processing'
)
class TestProcessorNode(BaseNode):
    """
    Node that processes TestData custom type from test_a library.
    
    Demonstrates cross-library custom type usage.
    """
    
    def __init__(self, node_id, wrapper):
        super().__init__(node_id, wrapper)
        
        # Configure behavior
        self.behavior.is_data_node = True
        self.behavior.is_control_node = False
        
    def initialize(self):

        from haybale_core.types.specs import FLOAT, STRING
        from haybale_core.widgets.basic_widgets import SliderWidget, NumberWidget

        # Import the custom type from test_a library
        from haybale_test_a.types.data import TestData

        # Input: Custom TestData type
        self.add(TestData.as_inlet(    
                id='test_data_in',
                label='Test Data In'
            )
        )

        self.add(FLOAT.as_inlet(
                id='float_slider',
                label='Float Slider',
                widget=SliderWidget.config(properties={'min': 0.0, 'max': 100.0, 'step': 1}),
                default=50.0
            )
        )

        # Input: Additional value to add
        self.add(FLOAT.as_inlet(
                id='modifier',
                label='Modifier',
                default=1.0,
                widget=NumberWidget.config()
            )
        )
        
        # Output: Modified TestData
        self.add(TestData.as_outlet(
                id='test_data_out',
                label='Test Data Out'
            )
        )
        
        # Output: String description
        self.add(STRING.as_outlet(
                id='description',
                label='Description'
            )
        )

    def worker(self, context: dict) -> dict | None:
        """
        Process the TestData.
        
        Args:
            context: Execution context with input values
            
        Returns:
            Dictionary with output values
        """
        test_data_in = context.get('test_data_in')
        modifier = context.get('modifier', 1.0)
        
        if test_data_in is None:
            # Create a new TestData if none provided
            test_data_out = TestData(
                value=modifier,
                label="Generated by Test Processor",
                metadata={"source": "test_processor_node"}
            )
        else:
            # Process existing TestData
            test_data_out = TestData(
                value=(
                    test_data_in.value 
                    if test_data_in.value is None 
                    else test_data_in.value + modifier
                ),
                label=f"Processed: {test_data_in.label}",
                metadata={**test_data_in.metadata, "processed_by": "test_b.test_processor"}
            )
            test_data_out.add_metadata("modifier_applied", modifier)
        
        description = str(test_data_out)
        
        print(f"Test Processor [{self.node_id}]: {description}")
        
        return {
            'test_data_out': test_data_out,
            'description': description
        }
