"""Signal — base class for everything dispatched through SignalBus.

Concrete signal classes (`SelectionMoved`, `GraphDataMutated`, etc.)
inherit directly. `CommandSignal` is the imperative-flavored sub-base.

Synthetic signal classes generated by `signal_field()` also inherit
`Signal` directly — they participate as first-class subclasses with no
special routing.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import ClassVar


@dataclass(frozen=True, kw_only=True)
class Signal:
    """Base class for everything dispatched through SignalBus.

    Subscribers filter with `isinstance(signal, SignalType)` — there is
    no framework-side identity machinery beyond `type(signal)` matching.

    `cross_session: ClassVar[bool] = False` opts a signal into
    SessionManager.broadcast routing when True.
    """

    cross_session: ClassVar[bool] = False


@dataclass(frozen=True, kw_only=True)
class CommandSignal(Signal):
    """Imperative signal — 'do Y'.

    Conventionally one subscriber per command type (the AppShell), but
    the bus does not enforce that. Travels through the same bus as every
    other signal; the split is vocabulary for authors.
    """
