[debug]
log_level = "INFO"
log_library = ""
log_node = ""
log_to_file = false
log_ui = ""

[haystack]
last_haystack_name = "Master"
new_counter = 9

[workbench]
theme = "studio:theme:workbench:HaywireDarkTheme"

[editor.pan_zoom]
hover_enter_delay = 200
hover_exit_delay = 0
hover_scale_cutoff_zoom = 0.3
hover_scale_enabled = false
hover_scale_max = 5.0
max_zoom = 1.8
min_zoom = 0.01
pan_sensitivity = 5.0
zoom_sensitivity = 0.56

[ui.debug_overlay]
enabled = false
position = "top-left"

[ui.minimap]
debug_info = false
enabled = true
ghost_opacity = 0.2
opacity = 1.0
position = "bottom-right"
width = 116

[debug.library.core]
log_level = ""

[ui.node.skin]
content_gap = -15
inspect_on_click = false
pin_gutter = 20
pin_protrusion = 0
show_labels = false
show_node_ids = false
show_resize_handle = false
show_tooltips = true
