[debug]
log_level = "WARNING"
log_library = ""
log_node = "DEBUG"

[workbench]
theme = "studio:theme:workbench:haywire-dark"

[editor.pan_zoom]
max_zoom = 3.4
min_zoom = 0.05
pan_sensitivity = 4.2
zoom_sensitivity = 0.4

[ui.minimap]
enabled = true
position = "bottom-right"
width = 259
