"""The rules for setting up and maintaining studio TLS.

This is the ``operations.py`` of the TLS feature: it composes
:mod:`~haywire_studio.network.names`, :mod:`~haywire_studio.network.certs` and
the security document into the four things a user can do, and it raises
:class:`~haywire_studio.network.certs.CertError` with a user-facing message.
It still prints nothing — the CLI owns output.

The split from ``certs.py`` is the same one ``roster.py``/``operations.py``
makes: that module is the material, this one is the policy. It exists so a
future settings-panel button can call the same functions as the CLI and cannot
drift into a second set of rules.
"""

from __future__ import annotations

import datetime
from collections.abc import Iterable
from dataclasses import dataclass
from enum import Enum
from pathlib import Path

from haywire_studio.network import certs
from haywire_studio.network.certs import CertError
from haywire_studio.network.names import LocalNames, local_names, primary_address
from haywire_studio.security.document import SecurityDocument, load_document
from haywire_studio.security.errors import SecurityError
from haywire_studio.security.operations import write_tls_paths

# Warn below this. Ten-year certificates make it rare, but a certificate
# generated by other means may be near its end.
_EXPIRY_WARNING = datetime.timedelta(days=30)

# Loopback names are structural: a certificate that cannot serve localhost
# breaks the default, loopback-only studio. They are never removable.
_PROTECTED = frozenset({"localhost", "127.0.0.1", "::1"})


class TlsState(Enum):
    """What ``ssl status`` found. Each state has exactly one next action.

    Four of these — ``FILE_MISSING``, ``HALF_CONFIGURED``, ``KEY_MISMATCH`` and
    an unreadable certificate — are the conditions that make the studio refuse
    to start. Catching them in a read-only command is strictly better than
    discovering them at boot, so the wording here mirrors the startup errors.
    """

    OFF_LOOPBACK = "off_loopback"
    OFF_EXPOSED = "off_exposed"
    OK = "ok"
    NOT_COVERED = "not_covered"
    FILE_MISSING = "file_missing"
    HALF_CONFIGURED = "half_configured"
    ORPHANED = "orphaned"
    KEY_MISMATCH = "key_mismatch"
    UNREADABLE = "unreadable"
    EXPIRING = "expiring"


@dataclass(frozen=True)
class TlsStatus:
    """Everything ``ssl status`` needs, gathered without judging it."""

    state: TlsState
    certfile: str
    keyfile: str
    covered: LocalNames
    reachable_at: str | None
    exposed: bool
    expires: datetime.datetime | None
    fingerprint: str | None
    detail: str

    @property
    def configured(self) -> bool:
        """Both paths set. Sequential rather than ``and`` so each half is
        separately readable — exactly one of the pair is the HALF_CONFIGURED
        state that hard-exits the studio, so the two are not interchangeable."""
        if not self.certfile:
            return False
        if not self.keyfile:
            return False
        return True

    def covered_alternative(self) -> str | None:
        """A DNS name the certificate already covers, for the NOT_COVERED case.

        Often the user needs no action at all — the ``.local`` name still
        works — and saying so beats making them re-run a command.
        """
        for name in self.covered.dns:
            if name.endswith(".local"):
                return name
        return None


@dataclass(frozen=True)
class SetupResult:
    """What ``setup`` did, so the CLI can report it precisely."""

    covered: LocalNames
    cert_path: Path
    key_path: Path
    expires: datetime.datetime
    fingerprint: str
    adopted: bool = False


def setup(
    extra_names: Iterable[str] | None = (),
    *,
    directory: Path | None = None,
    path: Path | None = None,
) -> SetupResult:
    """Create a certificate and point the studio at it.

    Refuses when TLS is already set up — that is ``update``'s job. The one
    exception is an *orphaned* certificate: files on disk that the settings do
    not reference. Regenerating there would silently invalidate a certificate
    the user may already have trusted on other machines, which is the worst
    available outcome, so the existing pair is adopted instead. The situation is
    unambiguous, which is why it is inferred rather than hidden behind a flag.
    """
    key_path, cert_path = certs.paths(directory)
    doc = load_document(path)
    configured_cert, configured_key = doc.network.tls_certfile, doc.network.tls_keyfile

    if _pair_on_disk(key_path, cert_path):
        if _any_path_configured(configured_cert, configured_key):
            raise CertError(
                "A certificate already exists and is configured.\n"
                "  Use 'haywire ssl update' to change which names it covers."
            )
        return _adopt(directory, path, cert_path, key_path)

    names = _names_for_setup(extra_names, path)
    key = certs.generate_key()
    cert = certs.sign_cert(key, names)
    written_key = certs.write_key(key, directory)
    written_cert = certs.write_cert(cert, directory)
    write_tls_paths(str(written_cert), str(written_key), path=path)

    return SetupResult(
        covered=names,
        cert_path=written_cert,
        key_path=written_key,
        expires=certs.cert_expiry(cert),
        fingerprint=certs.fingerprint(cert),
    )


def update(
    *,
    add: Iterable[str] | None = (),
    remove: Iterable[str] | None = (),
    refresh: bool = False,
    directory: Path | None = None,
    path: Path | None = None,
) -> SetupResult:
    """Re-sign the existing certificate with an amended name list.

    **The private key is reused** (D4). That keeps one ``0600`` key file rather
    than accumulating orphans, and makes the operation honestly an amendment.
    The certificate itself is new, so anything that trusted the old one must
    trust this one — the CLI is required to say so.
    """
    key_path, cert_path = certs.paths(directory)
    if not cert_path.exists():
        raise CertError("No certificate to update.\n  Run 'haywire ssl setup' to create one.")

    key = certs.load_key(directory)
    existing = certs.load_cert(directory)
    if not certs.key_matches_cert(key, existing):
        raise CertError(
            f"The key and certificate do not match:\n"
            f"  {key_path}\n  {cert_path}\n"
            "One of them has been replaced. Run 'haywire ssl setup' to make a new pair."
        )

    names = certs.cert_names(existing)
    if refresh:
        # Union with what this machine is reachable at *now*, preserving
        # anything added by hand. This is the home-to-university command.
        names = _union(names, local_names())
    names = names.extend(add)
    names = _remove(names, remove)

    cert = certs.sign_cert(key, names)
    written_cert = certs.write_cert(cert, directory)
    # The settings already point at these paths, so no settings write is
    # needed — unless the pair was never configured (an orphan being updated).
    doc = load_document(path)
    configured_cert, configured_key = doc.network.tls_certfile, doc.network.tls_keyfile
    if not _both_paths_configured(configured_cert, configured_key):
        write_tls_paths(str(written_cert), str(key_path), path=path)

    return SetupResult(
        covered=names,
        cert_path=written_cert,
        key_path=key_path,
        expires=certs.cert_expiry(cert),
        fingerprint=certs.fingerprint(cert),
    )


def status(
    *,
    directory: Path | None = None,
    path: Path | None = None,
    document: SecurityDocument | None = None,
) -> TlsStatus:
    """Classify the current TLS setup. Never raises.

    *document* short-circuits the disk read — that is what lets the studio's
    Security panel report the configuration actually in force rather than
    whatever has since been written to the file.

    Deliberately does **not** probe any OS trust store: doing that portably is
    genuinely hard, and wrongly reporting "trusted" is worse than not reporting
    it at all. Report what the files say; let ``trust`` speak for itself.
    """
    doc = document if document is not None else _document_quietly(path)
    certfile, keyfile = doc.network.tls_certfile, doc.network.tls_keyfile
    exposed = doc.network.exposed
    reachable = primary_address()
    key_path, cert_path = certs.paths(directory)

    blank = LocalNames.empty()

    if bool(certfile) != bool(keyfile):
        missing = "tls_keyfile" if certfile else "tls_certfile"
        return _status(
            TlsState.HALF_CONFIGURED,
            certfile,
            keyfile,
            blank,
            reachable,
            exposed,
            detail=f"{missing} is empty; set both or neither.",
        )

    if not certfile:
        # keyfile is necessarily empty too — the mismatched case returned above.
        if _pair_on_disk(key_path, cert_path):
            return _status(
                TlsState.ORPHANED,
                certfile,
                keyfile,
                blank,
                reachable,
                exposed,
                detail=f"A certificate exists at {cert_path} but nothing points at it.",
            )
        state = TlsState.OFF_EXPOSED if exposed else TlsState.OFF_LOOPBACK
        return _status(state, certfile, keyfile, blank, reachable, exposed, detail="")

    for label, value in (("tls_certfile", certfile), ("tls_keyfile", keyfile)):
        if not Path(value).is_file():
            return _status(
                TlsState.FILE_MISSING,
                certfile,
                keyfile,
                blank,
                reachable,
                exposed,
                detail=f"{label} does not point at a file: {value}",
            )

    try:
        cert = certs.load_cert(directory)
    except CertError as exc:
        return _status(TlsState.UNREADABLE, certfile, keyfile, blank, reachable, exposed, detail=str(exc))

    covered = certs.cert_names(cert)
    expires = certs.cert_expiry(cert)
    thumb = certs.fingerprint(cert)

    try:
        if not certs.key_matches_cert(certs.load_key(directory), cert):
            return _status(
                TlsState.KEY_MISMATCH,
                certfile,
                keyfile,
                covered,
                reachable,
                exposed,
                expires=expires,
                fingerprint=thumb,
                detail=f"The key and certificate do not match:\n  {keyfile}\n  {certfile}",
            )
    except CertError as exc:
        return _status(
            TlsState.UNREADABLE,
            certfile,
            keyfile,
            covered,
            reachable,
            exposed,
            expires=expires,
            fingerprint=thumb,
            detail=str(exc),
        )

    if _address_uncovered(reachable, covered):
        return _status(
            TlsState.NOT_COVERED,
            certfile,
            keyfile,
            covered,
            reachable,
            exposed,
            expires=expires,
            fingerprint=thumb,
            detail=f"{reachable} is not in the certificate's name list.",
        )

    remaining = expires - datetime.datetime.now(datetime.timezone.utc)
    if remaining < _EXPIRY_WARNING:
        return _status(
            TlsState.EXPIRING,
            certfile,
            keyfile,
            covered,
            reachable,
            exposed,
            expires=expires,
            fingerprint=thumb,
            detail=f"Expires in {max(remaining.days, 0)} day(s).",
        )

    return _status(
        TlsState.OK,
        certfile,
        keyfile,
        covered,
        reachable,
        exposed,
        expires=expires,
        fingerprint=thumb,
        detail="",
    )


def _document_quietly(path: Path | None) -> SecurityDocument:
    """The document, or an empty one. ``status`` runs against whatever is on
    disk — including a broken file, which is precisely the situation the user
    needs reported, so it must not raise here."""
    try:
        return load_document(path)
    except SecurityError:
        return SecurityDocument()


def trust_command(directory: Path | None = None, *, platform: str | None = None) -> str:
    """The platform command that makes this machine trust the certificate.

    Returned as text, never executed: it needs ``sudo`` and it modifies the
    machine's trust store, which is not something a subcommand should do
    unannounced.
    """
    import sys

    _, cert_path = certs.paths(directory)
    system = platform or sys.platform

    if system == "darwin":
        return (
            "sudo security add-trusted-cert -d -r trustRoot \\\n"
            f"     -k /Library/Keychains/System.keychain {cert_path}"
        )
    if system.startswith("win"):
        return f"Import-Certificate -FilePath {cert_path} -CertStoreLocation Cert:\\LocalMachine\\Root"
    return (
        f"sudo cp {cert_path} /usr/local/share/ca-certificates/haywire-studio.crt \\\n"
        "  && sudo update-ca-certificates"
    )


def _pair_on_disk(key_path: Path, cert_path: Path) -> bool:
    """Both halves of a certificate pair present on disk.

    Sequential rather than ``and``: a lone key or a lone certificate is not an
    orphan to adopt, and reading the two checks separately is what makes that
    obvious.
    """
    if not cert_path.exists():
        return False
    if not key_path.exists():
        return False
    return True


def _any_path_configured(configured_cert: str, configured_key: str) -> bool:
    """Either TLS path set in settings.

    Deliberately "either", not "both": one alone is the HALF_CONFIGURED state,
    and treating it as unconfigured would let ``setup`` overwrite a half-written
    configuration instead of refusing.
    """
    if configured_cert:
        return True
    if configured_key:
        return True
    return False


def _both_paths_configured(configured_cert: str, configured_key: str) -> bool:
    """Both TLS paths set in settings — a complete configuration.

    The complement of :func:`_any_path_configured`, and NOT interchangeable
    with it: half a configuration must read as "needs writing" here, but as
    "already exists, refuse" there.
    """
    if not configured_cert:
        return False
    if not configured_key:
        return False
    return True


def _address_uncovered(reachable: str | None, covered: LocalNames) -> bool:
    """True when this machine's address exists and the certificate omits it.

    An undetectable address is **not** reported as uncovered — claiming a
    coverage gap that may not exist would send the user to re-issue a working
    certificate.
    """
    if reachable is None:
        return False
    if covered.covers(reachable):
        return False
    return True


def _adopt(
    directory: Path | None,
    path: Path | None,
    cert_path: Path,
    key_path: Path,
) -> SetupResult:
    """Wire settings up to a certificate that already exists on disk."""
    cert = certs.load_cert(directory)
    write_tls_paths(str(cert_path), str(key_path), path=path)
    return SetupResult(
        covered=certs.cert_names(cert),
        cert_path=cert_path,
        key_path=key_path,
        expires=certs.cert_expiry(cert),
        fingerprint=certs.fingerprint(cert),
        adopted=True,
    )


def _names_for_setup(extra_names: Iterable[str] | None, path: Path | None) -> LocalNames:
    """Local names, plus anything the user asked for, plus public_hostname."""
    names = local_names().extend(extra_names)
    hostname = _document_quietly(path).network.public_hostname
    if hostname.strip():
        names = names.extend([hostname])
    return names


def _union(base: LocalNames, other: LocalNames) -> LocalNames:
    """Merge *other* into *base*, preserving manually-added names."""
    return base.extend(list(other.dns) + list(other.ip))


def _remove(names: LocalNames, targets: Iterable[str] | None) -> LocalNames:
    """Drop names, refusing to strip loopback."""
    drop = {str(entry).strip() for entry in (targets or ()) if str(entry).strip()}
    if not drop:
        return names
    protected = drop & _PROTECTED
    if protected:
        raise CertError(
            f"{', '.join(sorted(protected))} cannot be removed — "
            "a certificate that cannot serve localhost breaks the default studio."
        )
    return LocalNames(
        dns=tuple(name for name in names.dns if name not in drop),
        ip=tuple(name for name in names.ip if name not in drop),
    )


def _status(
    state: TlsState,
    certfile: str,
    keyfile: str,
    covered: LocalNames,
    reachable: str | None,
    exposed: bool,
    *,
    expires: datetime.datetime | None = None,
    fingerprint: str | None = None,
    detail: str = "",
) -> TlsStatus:
    return TlsStatus(
        state=state,
        certfile=certfile,
        keyfile=keyfile,
        covered=covered,
        reachable_at=reachable,
        exposed=exposed,
        expires=expires,
        fingerprint=fingerprint,
        detail=detail,
    )
