[project]
name = "haybale-studio"
version = "0.0.39"
description = "Library for haywire studio"
requires-python = ">=3.12"
license = {text = "MIT"}

dependencies = [
    "haywire-core>=0.0.39",
    "nicegui>=3.12.1",
]
keywords = ["experimental", "project-local"]

[project.entry-points."haywire.libraries"]
studio = "haybale_studio:Library"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["haybale_studio"]
