"""
Test Processor Node

This node demonstrates using a custom type from another library.
It uses TestData from test_a library.
"""

from haywire.core.node.base_node import node, BaseNode
from haywire.core.node.ports import PortInlet, PortOutlet
from haywire.core.data.enums import FlowType
from haywire.core.data.fields import SingleField

# Import the custom type from test_a library
from haybale_test_a.types.data import TestData

@node(
    label='Test Processor',
    description='Processes TestData from test_a library',
    search_tags=['test', 'processor', 'cross-library'],
    menu='test_b/processing'
)
class TestProcessorNode(BaseNode):
    """
    Node that processes TestData custom type from test_a library.
    
    Demonstrates cross-library custom type usage.
    """
    
    def __init__(self, node_id, graph):
        super().__init__(node_id, graph)
        
        # Configure behavior
        self.behavior.is_data_node = True
        self.behavior.is_control_node = False
        
        # Input: Custom TestData type
        self.add_inlet(
            PortInlet(
                id='test_data_in',
                label='Test Data In',
                cls_type=TestData,
                flow_type=FlowType.DATA,
                data=SingleField(TestData, None, False),
                widget='core.text'
            )
        )
        
        # Input: Additional value to add
        self.add_inlet(
            PortInlet(
                id='modifier',
                label='Modifier',
                cls_type=float,
                flow_type=FlowType.DATA,
                data=SingleField(float, 1.0, False),
                widget='core.number'
            )
        )
        
        # Output: Modified TestData
        self.add_outlet(
            PortOutlet(
                id='test_data_out',
                cls_type=TestData,
                flow_type=FlowType.DATA,
                label='Test Data Out',
                data=SingleField(TestData, None, False)
            )
        )
        
        # Output: String description
        self.add_outlet(
            PortOutlet(
                id='description',
                cls_type=str,
                flow_type=FlowType.DATA,
                label='Description',
                data=SingleField(str, None, False)
            )
        )
    
    def worker(self, context: dict) -> dict | None:
        """
        Process the TestData.
        
        Args:
            context: Execution context with input values
            
        Returns:
            Dictionary with output values
        """
        test_data_in = context.get('test_data_in')
        modifier = context.get('modifier', 1.0)
        
        if test_data_in is None:
            # Create a new TestData if none provided
            test_data_out = TestData(
                value=modifier,
                label="Generated by Test Processor",
                metadata={"source": "test_processor_node"}
            )
        else:
            # Process existing TestData
            test_data_out = TestData(
                value=test_data_in.value if test_data_in.value is None else test_data_in.value + modifier,
                label=f"Processed: {test_data_in.label}",
                metadata={**test_data_in.metadata, "processed_by": "test_b.test_processor"}
            )
            test_data_out.add_metadata("modifier_applied", modifier)
        
        description = str(test_data_out)
        
        print(f"Test Processor [{self.node_id}]: {description}")
        
        return {
            'test_data_out': test_data_out,
            'description': description
        }
