"""Generate the official two-tier haywire feed (spec §11).

Output layout written under ``--out-dir``:

    <out-dir>/
    ├── marketplace.toml        # aggregator with one [[stalls]] per library
    └── stalls/
        ├── haybale-core.toml   # marketstall with exactly one [[haybales]]
        ├── haybale-studio.toml
        └── ...                 # one per publish_order entry

Reads [tool.haywire.release] (publish_order) and [tool.haywire.marketstall]
(source_url, docs_branch, feed_base_url) from the workspace root pyproject,
builds each publishable package's row with the same builder the share
pipeline uses (``haybale.toml`` is canon), and emits the two-tier layout.
Source is "pypi" for packages in pip_publish_order and "git" for packages
in git_publish_order. Deployed by the publish CI workflow (T4) to GitHub
Pages.

Used by:
  - .github/workflows/publish.yml (job 4 — deploy marketstall)
  - manual invocation: uv run python scripts/generate_marketstall.py
"""

from __future__ import annotations

import argparse
import sys
import tomllib
from dataclasses import dataclass
from pathlib import Path

from haywire.core.publishing.marketstall import _build_entry_for_library


@dataclass(frozen=True)
class MarketstallConfig:
    """Repo-level config consumed by build_entry. Read from [tool.haywire.marketstall].

    ``feed_base_url`` (spec §11) is the deployed-feed root; the generator
    composes per-stall URLs as ``{feed_base_url}/stalls/{dist-name}.toml``.
    ``marketplace`` is the explicit allowlist of package names that appear in
    the official feed. Source (pypi vs git) is derived by lookup against the
    release config's pip_publish_order / git_publish_order.
    """

    source_url: str
    docs_branch: str
    feed_base_url: str
    marketplace: list[str]


def read_marketstall_config(root_pyproject: Path) -> MarketstallConfig:
    data = tomllib.loads(root_pyproject.read_text(encoding="utf-8"))
    block = data["tool"]["haywire"]["marketstall"]
    return MarketstallConfig(
        source_url=block["source_url"],
        docs_branch=block.get("docs_branch", "main"),
        feed_base_url=block.get("feed_base_url", "").rstrip("/"),
        marketplace=list(block.get("marketplace", [])),
    )


def build_entry(
    pkg_dir: Path,
    source: str = "pypi",
) -> dict[str, object]:
    """Build one [[haybales]] dict for a package, via the shared marketstall builder.

    `pkg_dir` is the package directory (holding pyproject.toml and the module
    dir with haybale.toml). `source` is "pypi" (default; install_spec becomes
    `{name}=={version}`) or "git" (a git+subdirectory VCS install_spec).

    Everything — including the install_spec — comes from
    `_build_entry_for_library`, the same function the share pipeline uses, so
    the two publishers cannot drift apart. This used to override `install_spec`
    after the fact with the bare dist name, which meant a row advertised one
    version and installed whatever PyPI currently served: the studio's update
    check (`installed < row.version`) then never settled, and clicking Update
    reinstalled the same thing.
    """
    entry = _build_entry_for_library(pkg_dir, distribute=source)
    if entry is None:
        raise ValueError(f"{pkg_dir} has no pyproject.toml — cannot build a marketstall entry")
    return entry


# Order of fields in every [[haybales]] entry. Matches Haybale._TOML_FIELDS —
# the same order the runtime parsers and the share pipeline emit, so a
# generated stall and a wizard-published marketstall.toml are byte-shape
# compatible.
_ENTRY_FIELD_ORDER: tuple[str, ...] = (
    "name",
    "label",
    "version",
    "require",
    "description",
    "source",
    "install_spec",
    "tags",
    "os",
    "on_reload",
    "linked_libraries",
    "origin",
    "origin_provider",
    "notes",
    "homepage_url",
    "documentation_url",
    "issues_url",
    "examples_path",
    "tests_path",
    "via",
    "last_seen",
    "stale",
    "authors",
    "deprecated",
)

_MARKETPLACE_HEADER = """\
# Official haywire marketplace — aggregator (spec §11)
# Generated by scripts/generate_marketstall.py on every release tag.
# Do not edit by hand — re-run the generator instead.
#
# Subscribers fetch this file from GitHub Pages:
#   https://going-haywire.github.io/haywire/marketplace.toml
#
# Per-library marketstalls live under stalls/<dist-name>.toml; a consumer who
# wants only one library can subscribe to that stall URL directly.
"""

_STALL_HEADER = """\
# Marketstall for {name} (auto-generated; spec §2)
# Source of truth: the package's haybale.toml in the haywire monorepo.
# Re-generated on every release tag by scripts/generate_marketstall.py.
"""


def emit_stall_toml(entry: dict[str, object]) -> str:
    """Emit a marketstall TOML with one ``[[haybales]]`` section for ``entry``.

    Field order follows the runtime ``Haybale._TOML_FIELDS`` definition.
    """
    parts: list[str] = [_STALL_HEADER.format(name=entry.get("name", ""))]
    parts.append("")
    parts.append("[[haybales]]")
    for field in _ENTRY_FIELD_ORDER:
        if field not in entry:
            continue
        parts.append(f"{field} = {_format_value(entry[field])}")
    parts.append("")
    return "\n".join(parts)


def emit_marketplace_toml(stall_urls: list[str]) -> str:
    """Emit the aggregator marketplace TOML referencing one ``[[stalls]]`` per URL.

    ``url`` only: ``preference`` and ``blocked`` are a *consumer's* local
    opinion about their own subscriptions, and the remote parser reads nothing
    but ``url`` from a published feed. Emitting them here wrote three arrays
    nobody could act on and implied the publisher had a say in them.
    """
    parts: list[str] = [_MARKETPLACE_HEADER]
    for url in stall_urls:
        parts.append("")
        parts.append("[[stalls]]")
        parts.append(f"url = {_format_string(url)}")
    parts.append("")
    return "\n".join(parts)


def _format_value(value: object) -> str:
    if isinstance(value, str):
        return _format_string(value)
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, dict):
        return _format_inline_table(value)
    if isinstance(value, list):
        if not value:
            return "[]"
        return "[" + ", ".join(_format_value(v) for v in value) + "]"
    raise TypeError(f"unsupported marketstall value type: {type(value).__name__}")


def _format_inline_table(value: dict) -> str:
    """Format a dict as a TOML inline table: ``{ key = value, ... }``.

    Used for ``authors`` entries (``{name, url}``) and ``deprecated``
    (``{since, reason, successor}``) — both TOML-serializable dicts on
    ``Haybale.to_dict()`` that stay inside their parent bare key rather than
    opening a ``[[authors]]`` / ``[deprecated]`` section, so field order in
    ``_ENTRY_FIELD_ORDER`` is preserved regardless of where these fall.
    """
    return "{ " + ", ".join(f"{k} = {_format_value(v)}" for k, v in value.items()) + " }"


def _format_string(value: str) -> str:
    """Format a string as a TOML basic string.

    Escapes backslash, double quote, and the control characters TOML basic
    strings forbid (newline, carriage return, tab). Other control characters
    are rare in practice and would fail TOML parsing — we accept that and
    don't pre-validate.
    """
    escaped = (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
    )
    return f'"{escaped}"'


@dataclass(frozen=True)
class GenerateResult:
    """Output of :func:`generate` — one marketplace + one stall per library."""

    marketplace_toml: str
    stalls: list[tuple[str, str]]  # [(dist-name, stall-toml), ...] in publish order


def generate(root_pyproject: Path, *, feed_base_url: str | None = None) -> GenerateResult:
    """Build the two-tier official feed (spec §11) for the workspace.

    Reads:
      - [tool.haywire.release] pip_publish_order, git_publish_order
      - [tool.haywire.marketstall] marketplace (explicit allowlist), plus URL/defaults
      - each marketplace package's haybale.toml (via the shared builder)

    Validates:
      - Every marketplace entry appears in exactly one of pip_publish_order or
        git_publish_order (unknown name → ValueError).
      - No name may appear in both pip_publish_order and git_publish_order.

    Returns a :class:`GenerateResult` carrying:
      - ``marketplace_toml``: aggregator TOML with one ``[[stalls]]`` per entry
        in marketplace, URL = ``{feed_base_url}/stalls/{dist-name}.toml``.
      - ``stalls``: list of ``(dist-name, stall-toml)`` pairs in marketplace order.
    """
    from scripts.bump_version import locate_packages, read_release_config

    release = read_release_config(root_pyproject)
    config = read_marketstall_config(root_pyproject)

    base_url = (feed_base_url or config.feed_base_url).rstrip("/")
    if not base_url:
        raise ValueError(
            "feed_base_url is required: set [tool.haywire.marketstall].feed_base_url "
            "in pyproject.toml or pass --feed-base-url on the command line."
        )

    pip_set = set(release.pip_publish_order)
    git_set = set(release.git_publish_order)

    # Validate: no package in both lists.
    both = pip_set & git_set
    if both:
        raise ValueError(
            f"packages appear in both pip_publish_order and git_publish_order: {sorted(both)}. "
            "A package can only have one source."
        )

    # Validate: every marketplace entry must be in exactly one publish list.
    marketplace_set = set(config.marketplace)
    unknown = marketplace_set - pip_set - git_set
    if unknown:
        raise ValueError(
            f"marketplace entries not found in pip_publish_order or git_publish_order: "
            f"{sorted(unknown)}. "
            "Add them to the appropriate publish list or remove them from marketplace."
        )

    located = locate_packages(root_pyproject, release)

    stalls: list[tuple[str, str]] = []
    stall_urls: list[str] = []

    for pkg_name in config.marketplace:
        source = "pypi" if pkg_name in pip_set else "git"
        # Resolved to absolute: _build_entry_for_library walks up from pkg_dir
        # to find the git root (`lib_dir.relative_to(git_root)`), which raises
        # ValueError if pkg_dir is relative while the discovered git root is
        # absolute — as it always is, since `_find_git_root` resolves.
        pkg_dir = located[pkg_name].parent.resolve()
        entry = build_entry(pkg_dir, source=source)
        dist_name = str(entry["name"])
        stalls.append((dist_name, emit_stall_toml(entry)))
        stall_urls.append(f"{base_url}/stalls/{dist_name}.toml")

    return GenerateResult(
        marketplace_toml=emit_marketplace_toml(stall_urls),
        stalls=stalls,
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="generate_marketstall",
        description="Generate the official two-tier haywire feed (spec §11).",
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=Path("pyproject.toml"),
        help="Path to the workspace root pyproject.toml (default: ./pyproject.toml).",
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        required=True,
        help="Output directory. Will contain marketplace.toml and stalls/<dist>.toml.",
    )
    parser.add_argument(
        "--feed-base-url",
        default=None,
        help=(
            "Override [tool.haywire.marketstall].feed_base_url — the deployed-feed "
            "root used to build per-stall subscription URLs."
        ),
    )
    args = parser.parse_args(argv)

    result = generate(args.root, feed_base_url=args.feed_base_url)

    out_dir: Path = args.out_dir
    stalls_dir = out_dir / "stalls"
    stalls_dir.mkdir(parents=True, exist_ok=True)

    marketplace_path = out_dir / "marketplace.toml"
    marketplace_path.write_text(result.marketplace_toml, encoding="utf-8")
    print(f"Wrote {marketplace_path}", file=sys.stderr)

    for dist_name, stall_body in result.stalls:
        stall_path = stalls_dir / f"{dist_name}.toml"
        stall_path.write_text(stall_body, encoding="utf-8")
        print(f"Wrote {stall_path}", file=sys.stderr)

    return 0


if __name__ == "__main__":
    # When run as `python scripts/generate_marketstall.py`, the script's own
    # directory (not the repo root) is on sys.path, so `from scripts.bump_version
    # import ...` inside generate() fails. Prepend the repo root so the import
    # resolves. The `python -m scripts.generate_marketstall` form already works
    # because -m puts CWD on sys.path.
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
    sys.exit(main())
